export const initialState = {
  text: "Start Tuning!",
  style: {
    backgroundImage: "linear-gradient(to left, lightblue, lightgreen)",
    border: "transparent",
    height: "100px",
    width: "300px",
    fontFamily: `"Source Sans Pro", sans-serif`,
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: " 35px",
    lineHeight: " 35px",
    textAlign: " center",
    color: "#5a5a5f",
    padding: "20px",
    marginLeft: " 50px",
    marginRight: " 50px",
    borderRadius: " 10px",
    marginTop: "30px",
  },
};

export const onClickState = {
  text: "",
  style: {
    border: "0px",
    height: "0px",
    width: "0px",
    fontWeight: 0,
    fontSize: 0,
    lineHeight: 0,
    paddingLeft: 0,
    paddingRight: 0,
    marginLeft: 0,
    marginRight: 0,
    borderRadius: 0,
  },
};

export const onEnterHover = {
  text: "Start Tuning!",
  style: {
    // backgroundImage: "linear-gradient(to left, #CFFAF8, #A2FFA2)",
    border: "transparent",
    height: "100px",
    width: "300px",
    fontFamily: `"Source Sans Pro", sans-serif`,
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: " 35px",
    lineHeight: " 35px",
    textAlign: " center",
    color: "#49494e",
    padding: "20px",
    marginLeft: " 50px",
    marginRight: " 50px",
    borderRadius: " 10px",
    cursor: "pointer",
    animationName: "buttons",
    animationDuration: ".5s",
    animationIterationCount: "1",
    marginTop: "30px",
    backgroundColor: "#fcfcfc",
  },
};
